### ISSUE TITLE
V3，似乎没能打开任务列表，实际已打开

### ISSUE THREAD

**Issue by bilibili20001** [MonsterNone/tmall-miao#177] opened 2022-05-23 13:38 UTC
索尼 Xperia 1 II，系统是安卓12，类原生
![Screenshot_20220523-213517](https://user-images.githubusercontent.com/70944645/169832007-4240213c-b81b-4511-acb3-b1625f684537.png)

**Comment by MonsterNone** [comment] 2022-05-23 23:53
Duplicate of #173

**Closed by MonsterNone** 2022-05-23 23:53 UTC
