### ISSUE TITLE
热爱奇旅抽奖不能加购

### ISSUE THREAD

**Issue by xiaozhi24** [MonsterNone/tmall-miao#229] opened 2022-05-31 04:30 UTC
手机型号是一加9rt
![36706C33EA8EAABA91376AAD4E6E48D0](https://user-images.githubusercontent.com/50169742/171093080-ec2b8fd2-589b-44eb-b3e1-ca5a64341084.jpg)

**Comment by MonsterNone** [comment] 2022-06-01 00:17
Duplicate of #206

**Closed by MonsterNone** 2022-06-01 00:17 UTC
